name: Find Unity Project Path

on: workflow_dispatch

jobs:
  find-project-path:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List current directory
        run: Get-ChildItem -Path . -Force | Format-Table -AutoSize

      - name: Find Unity ProjectSettings directory
        run: |
          $projectSettingsPaths = Get-ChildItem -Path . -Recurse -Filter "ProjectSettings" -Directory
          foreach ($path in $projectSettingsPaths) {
            $projectPath = $path.FullName
            Write-Output "Found Unity Project at: $($path.FullName)"
            Write-Output "Project Path: $($path.Parent.FullName)"
          }
