name: Find Unity Project Path

on: workflow_dispatch

jobs:
  find-project-path:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List current directory
        run: Get-ChildItem -Path . -Force | Format-Table -AutoSize

      - name: Find Unity ProjectSettings directory
        run: |
          $projectSettingsPaths = Get-ChildItem -Path . -Recurse -Directory -Name "ProjectSettings"
          foreach ($path in $projectSettingsPaths) {
            $projectPath = [System.IO.Path]::GetDirectoryName($path)
            Write-Output "Found Unity Project at: $path"
            Write-Output "Project Path: $projectPath"
          }
        shell: pwsh
