name: Unity Build 🏗️

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/Library
          key: Library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: '2020.3.6f1'
          targetPlatform: StandaloneWindows64
          projectPath: '.' 

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: UnityBuild
          path: build/${{ matrix.targetPlatform }}/
